[workspace]
members = [
    "crates/contracts/core",
    "crates/tools"
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = "20.5.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = true
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
